name: Android CI
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3

      - name: Execute Gradle Clean
        run: ./gradlew clean

      - name: Execute Gradle Lint
        run: ./gradlew lint

      - name: Execute Gradle build
        run: ./gradlew build
